name: ci

on:
   pull_request:
      branches:
         - main

jobs:
   typecheck:
      name: "Typecheck and Build"
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-node@v4
           with:
              node-version: 22
         - uses: pnpm/action-setup@v4
         - name: Install dependencies
           run: pnpm install --frozen-lockfile
         - name: Build workspace
           run: pnpm build
         - name: Linting check
           run: pnpm lint
         - name: Type check
           run: pnpm typecheck
